reviews:
  smart_review_skipping: true # Skips files with trivial changes
  profile: "chill" # Reduces the intensity of reviews, focusing on critical issues
  request_changes_workflow: false # Disables automatic change requests
  high_level_summary: true # Provides concise summaries instead of detailed comments
  poem: false # Disables whimsical poems in reviews
  collapse_walkthrough: true # Collapses detailed walkthroughs to reduce clutter
  auto_review:
    enabled: false # Disables automatic reviews
    drafts: false # Skips reviews for draft PRs
    base_branches: ["main", "master"] # Limits reviews to specific branches
ignored_branch: "dependabot/*, renovate/*" # Ignores branches like dependency updates
ignored_titles: "docs, documentation" # Skips PRs with these title snippets