name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug Firebase secrets (safe check)
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        run: |
           [ -z "$FIREBASE_PROJECT_ID" ] && echo "❌ PROJECT_ID missing" || echo "✅ PROJECT_ID present"
           [ -z "$FIREBASE_CLIENT_EMAIL" ] && echo "❌ CLIENT_EMAIL missing" || echo "✅ CLIENT_EMAIL present"
           [ -z "$FIREBASE_PRIVATE_KEY" ] && echo "❌ PRIVATE_KEY missing" || echo "✅ PRIVATE_KEY present"

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install socket server dependencies
        run: cd notakto-socket-server && pnpm install --frozen-lockfile

      - name: Run Biome CI
        run: |
          pnpm exec biome ci .
          cd notakto-socket-server && pnpm exec biome ci .

      - name: Run tests
        run: pnpm test

      - name: Build application using .env
        run: |
          # Load .env into environment
          export $(grep -v '^#' .env | xargs)
          pnpm build
